apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
spec:
  selector:
    matchLabels:
      name: worker-pod
      app: demo-voting-app
  template:
    metadata:
    name: worker-pod
    labels:
      name: worker-pod
      app: demo-voting-app
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1
